rollback the session after UNIQUE constraint failed exception
Here is the error message:
InvalidRequestError: This Session's transaction has been rolled
back due to a previous exception during flush. To begin a new
transaction with this Session, first issue Session.rollback().
Original exception was: (IntegrityError) UNIQUE constraint failed:
version.id u'INSERT INTO version (id) VALUES (?)' (1,)

Signed-off-by: Harrison Feng <harrison_feng@163.com>